### ISSUE TITLE
How to make this work for instance launched via CloudFormation

### ISSUE THREAD

**Issue by deejanu** [peterpakos/cloud_tools#1]
Thank you. This works great with EC2 instances when I launch via EC2 console. I have CloudFormation templates to launch instances. Instances launched through CloudFormation do not get auto tagged.

**Comment by peterpakos** [comment]
In our environment all instances created by CFT get tagged within 5-10 minutes (CloudTrail logs are saved to S3 bucket every 5 minutes).

**Comment by deejanu** [comment]
Hmmm...I waited for couple hours but instances created from CFT template did not get autotagged. The only thing I changed in Python script was bucket name.
From: bucket = 'wandisco-%s-auto-tag' % profile
To: bucket = 'sometest' % profile
Is there anything else that needs to be changed in the script?

**Comment by deejanu** [comment]
I am wondering if it has anything to do with instances being launched from Service Catalog using CFT.

**Comment by peterpakos** [comment]
@deejanu, have you checked the CloudWatch logs for the output of the lambda function?

BTW, you can also run this function from CLI, just edit bucket name and provide profile and key (path to CloudTrail event log in S3 bucket) as arguments:

$ ./lambda_function PROFILE PATH

**Comment by deejanu** [comment]
It's working now but unfortunately because I launch the stack from the Service Catalog it creates this tag. 

Key: AutoTag_Creator
Value: arn:aws:sts::1234567890:assumed-role/LinuxUbuntuServerLaunchRole/servicecatalog

I logged in as username 'tester'. Wondering if there is a way to capture and tag username of authenticated user instead of assumed-role.

**Comment by peterpakos** [comment]
Unfortunately this is not something I've experienced myself.

I hope you found a solution for this.
